docs: configuring app names
surfstudio/surf-flutter-app-template pull request #101
Opened 2024-02-29 06:41 UTC by DmitrDomrachev

## Changes
- added instructions for configuring the names of different falvors builds

## Checklist for self-check
- [x] Commits and PRs have been filed according to [the rules on the project](https://github.com/surfstudio/surf-flutter-app-template#workflow-in-a-repository).
- [x] The author is marked as an assigne and assigned mandatory reviewers.
- [x] Required labels marked
- [x] Specified related tasks and/or related PRs.
- [x] Specified Changes.
- [ ] Attached videos/screenshots demonstrating the fix/feature.
- [x] All unspecified fields in the PR description deleted.
- [ ] New code covered by tests.

## Checklist for reviewers
- [ ] CI passed successfully _(with a green check mark)_.
- [ ] PR is atomic, by volume no more than 400 (+-) corrected lines (not including codogen).

Design:
- [ ] System design corresponds to the agreements on structure and architecture on the project.
- [ ] The code is decomposed into necessary and sufficient components.

Functionality:
- [ ] The code solves the problem.
- [ ] Any changes to the user interface are reasonable and look good.

Complexity:
- [ ] The code is clear, easy to read, functions are small, no more than 50 lines.
- [ ] The logic is not overcomplicated, there is no overengineering (no code sections that may be needed in the future, but no one knows about it).

Tests:
- [ ] Updated or added tests for mandatory components.
- [ ] The tests are correct, helpful, and well designed/developed.

Naming:
- [ ] The naming of variables, methods, classes and other components is understandable.

Comments:
- [ ] The comments are understandable and helpful.

Documentation:
- [ ] All labels are correct
- [ ] Technical documentation updated (after approval, updates last reviewer).

2024-03-01 12:28 UTC, dzmitry-struk-surf requested changes
In general - LGTM.

2024-03-01 12:28 UTC, dzmitry-struk-surf commented on docs/flavors.md
> +    }
We do not have `qa` flavor anymore in our template anymore. 
https://github.com/surfstudio/surf-flutter-app-template/pull/100

2024-03-01 12:28 UTC, dzmitry-struk-surf commented on docs/flavors.md
> +name, etc), you can create directory `qa` in `android/app/src` and put your files there.
Same as above.

2024-03-01 12:28 UTC, dzmitry-struk-surf commented on docs/flavors.md
> +   each of your new configuration. In the end you should have something like this:
Same as above.

2024-03-01 12:28 UTC, dzmitry-struk-surf commented on docs/flavors.md
> +  ]
Same as above.

2024-03-07 13:02 UTC, Sadhorsephile approved these changes

2024-03-07 13:02 UTC, merged