refactor: Debug feature refactor
surfstudio/surf-flutter-app-template pull request #102
Opened 2024-03-01 13:24 UTC by Evgenia-bit

## Changes
- refactor debug screen
- refactor uikit screen
- fixed tests

## Checklist for self-check
- [x] Commits and PRs have been filed according to [the rules on the project](https://github.com/surfstudio/surf-flutter-app-template#workflow-in-a-repository).
- [x] The author is marked as an assigne and assigned mandatory reviewers.
- [x] Required labels marked
- [ ] Specified related tasks and/or related PRs.
- [x] Specified Changes.
- [ ] Attached videos/screenshots demonstrating the fix/feature.
- [x] All unspecified fields in the PR description deleted.
- [ ] New code covered by tests.

## Checklist for reviewers
- [ ] CI passed successfully _(with a green check mark)_.
- [ ] PR is atomic, by volume no more than 400 (+-) corrected lines (not including codogen).

Design:
- [ ] System design corresponds to the agreements on structure and architecture on the project.
- [ ] The code is decomposed into necessary and sufficient components.

Functionality:
- [ ] The code solves the problem.
- [ ] Any changes to the user interface are reasonable and look good.

Complexity:
- [ ] The code is clear, easy to read, functions are small, no more than 50 lines.
- [ ] The logic is not overcomplicated, there is no overengineering (no code sections that may be needed in the future, but no one knows about it).

Tests:
- [ ] Updated or added tests for mandatory components.
- [ ] The tests are correct, helpful, and well designed/developed.

Naming:
- [ ] The naming of variables, methods, classes and other components is understandable.

Comments:
- [ ] The comments are understandable and helpful.

Documentation:
- [ ] All labels are correct
- [ ] Technical documentation updated (after approval, updates last reviewer).

2024-03-04 06:38 UTC, dzmitry-struk-surf requested changes
In general - nice refactoring.

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/features/debug/data/repositories/debug_repository.dart
> +      return Result.failed(Failure(original: e, trace: s));
ConfigStorage can't throw DioException. Let's leave just one catch.

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/features/debug/data/repositories/debug_repository.dart
> +      return Result.failed(Failure(original: e, trace: s));
Same as above.

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/features/debug/presentation/screens/debug/debug_model.dart
> +  ValueListenable<Url> get serverUrlState => _serverUrlState;
As far as I can see it is pure UI state. So it should be in `wm`, not in `model`.

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/features/debug/presentation/screens/debug/debug_model.dart
> +  // TODO(Evgenia-bit): убрать игнор после мержа ветки SNP-857-api в main
Leave comments in English, please.

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/features/debug/presentation/screens/debug/debug_wm.dart
> +    // TODO(Evgenia-bit): добавится изменение темы, когда ветка с рефакторингом сервиса темы будет смержена.
Leave comments in English, please.

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/features/debug/presentation/screens/debug/debug_wm.dart
> +  late final ScaffoldMessengerState _scaffoldMessenger;
I don't think that we need `late final` variable. We can inject `ScaffoldMessengerState` through `DebugScreenWM` constructor.

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/features/debug/presentation/screens/debug/debug_wm.dart
> +  void openUiKit() => _router.push(UiKitRouter());
You can add `const` constructor here.

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/features/debug/presentation/screens/ui_kit/ui_kit_screen.dart
Let's also add `UIKitFlow`. Without scope, just `UIKitFlow`.

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/features/debug/presentation/screens/debug/debug_screen.dart
Let's also add `DebugFlow`. Without scope, just `DebugFlow`.

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/features/debug/presentation/screens/ui_kit/ui_kit_wm.dart
> +abstract class IUiKitWM with ILocalizationMixin, ThemeIModelMixin implements IWidgetModel {
```suggestion
abstract interface class IUiKitWM with ILocalizationMixin, ThemeIModelMixin implements IWidgetModel {
```

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/features/debug/presentation/screens/debug/debug_wm.dart
> +abstract class IDebugScreenWM with ILocalizationMixin implements IWidgetModel {
```suggestion
abstract interface class IDebugScreenWM with ILocalizationMixin implements IWidgetModel {
```

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/features/debug/presentation/screens/ui_kit/ui_kit_wm.dart
> +  late final ScaffoldMessengerState _scaffoldMessenger;
I don't think that we need `late final` variable. We can inject `ScaffoldMessengerState` through `UiKitWM` constructor.

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/features/debug/presentation/screens/ui_kit/ui_kit_wm.dart
> +  void switchTheme() => context.read<IAppScope>().themeService.switchTheme();
You should change it after main branch merging.

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/features/navigation/service/router.dart
> +  replaceInRouteName: 'Flow|Screen,Route',
You should leave just `Flow` here and add DebugFlow and UiKitFlow as I mentioned above.

2024-03-04 06:38 UTC, dzmitry-struk-surf commented on lib/persistence/storage/config_storage/config_storage.dart
I suggest to make `getProxyUrl` and `getUrlType` synchronous functions. What do you think?

2024-03-04 08:37 UTC, Evgenia-bit commented on lib/features/debug/presentation/screens/ui_kit/ui_kit_screen.dart
maybe it's worth fixing in the documentation that the screens have an entry point?

2024-03-04 08:52 UTC, Evgenia-bit commented on lib/features/debug/presentation/screens/ui_kit/ui_kit_screen.dart
<img width="794" alt="Screenshot 2024-03-04 at 11 51 13" src="https://github.com/surfstudio/surf-flutter-app-template/assets/63193897/439e18e1-c64f-45b0-ab9b-48de40f8b307">
currently, flow is added only for subfeature

2024-03-04 09:09 UTC, dzmitry-struk-surf commented on lib/features/debug/presentation/screens/ui_kit/ui_kit_screen.dart
From my point of view, screen and subfeature - are quite the same, what do you think? I think that we should not use screen as it is now in docs, let's remove it and leave just subfeature.

2024-03-04 09:11 UTC, dzmitry-struk-surf commented on lib/features/debug/presentation/screens/debug/debug_screen.dart
You should move `DebugFlow` to the `debug` folder, it should not be  in the root.

2024-03-06 08:43 UTC, Sadhorsephile approved these changes

2024-03-06 08:45 UTC, merged