feat(SNP-1239): Permission handler
surfstudio/surf-flutter-app-template pull request #117
Opened 2024-04-12 15:12 UTC by internetova

## Checklist
- Add Permission handler
- Add example

https://github.com/surfstudio/surf-flutter-app-template/assets/39735343/c0d5c69d-c691-4cfd-8146-826923ad9817

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Is there an existing issue for this PR?
  - _link issue here_ (use keywords like `fix`, `close`, `resolve` etc. if necessary)
- [ ] Have the files been linted and formatted?
- [ ] Have the docs been updated to match the changes in the PR?
- [ ] Have the tests been updated to match the changes in the PR?
- [x] Attached videos/screenshots demonstrating the fix/feature.
- [ ] Have you run the tests locally to confirm they pass?

## New Features

### What new capabilities does this PR add?

### What docs changes are needed to explain this?

2024-04-15 12:00 UTC, dzmitry-struk-surf requested changes
In general: do we need this functionality for all of our projects? I mean notifications and location permissions. It will be not really convenient take away them from our projects when not needed.
I think we do no need this functionality in the template, it can be like in knowledge base or whatever else but not in the template.

2024-04-15 12:00 UTC, dzmitry-struk-surf commented on lib/features/app/di/app_scope.dart
> +  IPermissionHandlerRepository get permissionHandlerRepository => _permissionHandlerRepository;
You should not use `late final` fields. All dependencies should be injected into `AppScope`'s constructor to keep `AppScope` clean.

2024-04-15 12:00 UTC, dzmitry-struk-surf commented on lib/features/debug/presentation/ui_kit/ui_kit_model.dart
> +  ///
Add comment.

2024-04-25 10:13 UTC, plasticfiresam commented
> In general: do we need this functionality for all of our projects?

We can use the same package to access the device file system/gallery/camera etc. This tends to be more common and adding the package to the template becomes more useful

2024-05-06 12:50 UTC, dzmitry-struk-surf requested changes
You should remove all code from this pr, and leave a single md file as a change.

2024-05-06 12:50 UTC, dzmitry-struk-surf commented on docs/permission_handler.md
There is a lot of Dart code in the following file. It can vary from project to project, so it is optional.

But I do not see any native configuration code/instructions/advices. Native configuration is always a tricky part, but from changes perspective it is always the most stable one. It definitely should be in this guide.

What do you think?

2024-05-06 12:50 UTC, dzmitry-struk-surf commented on docs/permission_handler.md
> +4) In the `permissions/domain/repositorie` directory create the file `i_permission_handler_repository.dart`:
`repositorie` typo

2024-05-06 12:50 UTC, dzmitry-struk-surf commented on docs/permission_handler.md
> + return Result.failed(PermissionException(original: null, trace: null)); }}
Code is not properly formatted.

2024-05-13 14:25 UTC, dzmitry-struk-surf commented on pubspec.yaml
> +  permission_handler: 11.3.1
Remove the dependency, update `pubspec.lock` and we are ready to merge it 🙌🏻

2024-05-13 14:45 UTC, dzmitry-struk-surf approved these changes

2024-05-13 14:45 UTC, merged