[SPT-51] Auto route migration
surfstudio/surf-flutter-app-template pull request #12
Opened 2022-07-20 11:17 UTC by mark-kascheev

Migrate a project from go_router to auto_route package

2022-07-20 14:21 UTC, coccyx-cyst commented on lib/features/navigation/service/router.dart
> +import 'package:flutter_template/features/debug/screens/debug_screen/debug_screen.dart';
💬 Для чистоты импортов, можно сделать файлик, который экспортирует файлы для каждой связки Elementary и импортировать его

2022-07-20 15:01 UTC, mark-kascheev commented on lib/features/navigation/service/router.dart
> +import 'package:flutter_template/features/debug/screens/debug_screen/debug_screen.dart';
Хорошая идея, добавлю

2022-07-20 15:55 UTC, dshevchenkoo commented
Не хватает обновленного пункта "Навигация" в README файле

2022-07-20 17:10 UTC, coccyx-cyst approved these changes

2022-07-20 17:11 UTC, coccyx-cyst commented on README.md
> +используются класс AppRouter и для вложенной - StackRouter. Несмотря на то что возможно обращение к ним напрямую по контексту,
🔥

2022-07-21 07:04 UTC, mark-kascheev commented on lib/features/navigation/service/router.dart
> +    debugRoutes,
✅

2022-07-21 12:37 UTC, coccyx-cyst requested changes

2022-07-21 12:37 UTC, coccyx-cyst commented on README.md
> +используются класс AppRouter и для вложенной - StackRouter. Несмотря на то что возможно обращение к ним напрямую по контексту,
StackRouter не прокидывается и не хранится в зависимостях, он прокидывается в Конструктор WM из контекста в фабричном методе связанном с этой WM (это делается для получения самого актуального Роутера стака навигации). Нужно поправить. В свою очередь, AppRouter хранится в AppScope зависимостях и достается оттуда (В принципе корректно описано в пр).

2022-07-21 13:08 UTC, merged