feat(SNP-1717): Add tailor - ThemeExtension generator
surfstudio/surf-flutter-app-template pull request #121
Opened 2024-07-17 13:27 UTC by Sadhorsephile

## Changes

- Add tailor
- Remove color palette

2024-07-18 10:55 UTC, mpkander requested changes
Waiting for successful CI build

2024-07-22 09:30 UTC, DmitrDomrachev commented
We also need to update the AppThemeData class according to the migration guide

https://docs.flutter.dev/release/breaking-changes/new-color-scheme-roles#migration-guide

2024-07-22 09:31 UTC, DmitrDomrachev commented
> Waiting for successful CI build
 cicd script was successfully executed

2024-07-25 12:02 UTC, mpkander approved these changes

2024-07-25 12:02 UTC, merged