SNP-23: added nav bar, different screens view for debug and release mode
surfstudio/surf-flutter-app-template pull request #18
Opened 2022-09-16 07:40 UTC by Elena-FrontendDev

2022-09-20 08:47 UTC, dshevchenkoo commented on lib/features/navigation/service/router.gr.dart
> +    DashRouter.name: (routeData) {
мы можем настроить игнорирование сгенеренных файлов, чтобы они не отображались в пр?

2022-09-20 09:18 UTC, arefimenko requested changes

2022-09-20 09:18 UTC, arefimenko commented on lib/features/navigation/domain/entity/temp/temp_routes.dart
> +        dashRoutes,
`TempScreen` точно ли открывается первым при открытии приложения? есть опасения что нет

варианты исправления
1. у `TempScreen` сделать `initial: true`
2. убрать роутер, который описан поверх `TempScreen` и `TempScreen` сделать первый по стеку в корне `router.dart`

2022-09-20 09:18 UTC, arefimenko commented on lib/features/navigation/domain/entity/temp/temp_routes.dart
> +        dashRoutes,
![Screenshot 2022-09-20 at 12 17 39](https://user-images.githubusercontent.com/54911543/191219444-a9e71aa4-e365-47b8-9864-90762c5e0bb8.png)

исходя из этого скрина и куска кода выше создалось дополнительно **два** роутера, поверх уже созданного первого, что оверхед и не нужно, `TempScreen` должен быть на месте `homeRoute`

2022-09-20 10:32 UTC, Elena-FrontendDev commented on lib/features/navigation/service/router.gr.dart
> +    DashRouter.name: (routeData) {
добавила в .gitignore генерируемые файлы

2022-09-20 10:33 UTC, Elena-FrontendDev commented on lib/features/navigation/domain/entity/temp/temp_routes.dart
> +        dashRoutes,
удалила homeRoute, вместо него tempRoute

2022-09-27 04:51 UTC, dshevchenkoo commented on .gitignore
> +*.gr.dart
я не совсем это имел ввиду, скорее про настройки самого гитхаба, чтобы он схлопывал строки с кодогеном

2022-09-27 04:56 UTC, merged