refactor: Feature dir structure
surfstudio/surf-flutter-app-template pull request #70
Opened 2024-02-08 07:15 UTC by Sadhorsephile

## Changes

- refactor feature dir structure according to Surf standarts
- refactor mason bricks
- actualize docs

## Checklist for self-check
- [x] Commits and PRs have been filed according to [the rules on the project](https://github.com/surfstudio/surf-flutter-app-template#workflow-in-a-repository).
- [x] The author is marked as an assigne and assigned mandatory reviewers.
- [x] Required labels marked
- [x] Specified related tasks and/or related PRs.
- [x] Specified Changes.
- [x] Attached videos/screenshots demonstrating the fix/feature.
- [x] All unspecified fields in the PR description deleted.
- [ ] New code covered by tests.

## Checklist for reviewers
- [ ] CI passed successfully _(with a green check mark)_.
- [ ] PR is atomic, by volume no more than 400 (+-) corrected lines (not including codogen).

Design:
- [ ] System design corresponds to the agreements on structure and architecture on the project.
- [ ] The code is decomposed into necessary and sufficient components.

Functionality:
- [ ] The code solves the problem.
- [ ] Any changes to the user interface are reasonable and look good.

Complexity:
- [ ] The code is clear, easy to read, functions are small, no more than 50 lines.
- [ ] The logic is not overcomplicated, there is no overengineering (no code sections that may be needed in the future, but no one knows about it).

Tests:
- [ ] Updated or added tests for mandatory components.
- [ ] The tests are correct, helpful, and well designed/developed.

Naming:
- [ ] The naming of variables, methods, classes and other components is understandable.

Comments:
- [ ] The comments are understandable and helpful.

Documentation:
- [ ] All labels are correct
- [ ] Technical documentation updated (after approval, updates last reviewer).

2024-02-19 07:04 UTC, dzmitry-struk-surf reviewed
Add `const` constructors for the repositories where it is possible, please.

2024-02-19 07:04 UTC, dzmitry-struk-surf commented on lib/features/info/presentation/screens/info/info_model.dart
> +class InfoModel extends ElementaryModel {}
```suggestion
final class InfoModel extends ElementaryModel {}
```

2024-02-19 07:04 UTC, dzmitry-struk-surf commented on lib/features/temp/data/repositories/temp_repository.dart
> +class TempRepository implements ITempRepository{}
```suggestion
final class TempRepository implements ITempRepository{}
```

2024-02-19 07:04 UTC, dzmitry-struk-surf commented on lib/features/temp/di/temp_scope.dart
> +class TempScope extends DisposableObject implements ITempScope {
```suggestion
final class TempScope extends DisposableObject implements ITempScope {
```

2024-02-19 07:04 UTC, dzmitry-struk-surf commented on lib/features/temp/presentation/screens/temp/temp_model.dart
> +class TempModel extends ElementaryModel implements ITempModel {
```suggestion
final class TempModel extends ElementaryModel implements ITempModel {
```

2024-02-19 07:04 UTC, dzmitry-struk-surf commented on lib/features/temp/presentation/screens/temp/temp_screen.dart
> +class TempScreen extends ElementaryWidget<TempWidgetModel> {
```suggestion
class TempScreen extends ElementaryWidget<ITempWidgetModel> {
```

2024-02-19 07:04 UTC, dzmitry-struk-surf commented on lib/features/temp/presentation/screens/temp/temp_screen.dart
> +  Widget build(TempWidgetModel wm) {
```suggestion
  Widget build(ITempWidgetModel wm) {
```

2024-02-19 07:04 UTC, dzmitry-struk-surf commented on lib/features/temp/presentation/screens/temp/temp_widget_model.dart
>        label: 'Dash screen',
This should be in localization.

2024-02-19 07:04 UTC, dzmitry-struk-surf commented on lib/features/temp/presentation/temp_flow.dart
> +  const TempFlow({super.key});
You should not use `@macro` without previously using the `@template`. 
Add `@template` and change `@macro` for the relevant class, not `scan_biomarkers_entry.class`.

2024-02-19 08:03 UTC, Evgenia-bit commented on docs/architecture_and_project_structure.md
> +              - mappers
you mean swap `data` and `domain`?

2024-02-19 08:21 UTC, Evgenia-bit commented on docs/architecture_and_project_structure.md
> +                        - model
do you really need to add it here, and not like this?:
<img width="302" alt="Screenshot 2024-02-19 at 11 20 59" src="https://github.com/surfstudio/surf-flutter-app-template/assets/63193897/ef3bea14-8312-424b-915e-b57b8b8ce99a">

2024-02-19 17:15 UTC, dzmitry-struk-surf requested changes

2024-02-19 17:15 UTC, dzmitry-struk-surf commented on docs/architecture_and_project_structure.md
> +                - {sub_feature_name/screen_name}_model.dart
Here it should be just:
```suggestion
                - {feature_name}_widget.dart
                - {feature_name}_wm.dart
                - {feature_name}_model.dart
```

2024-02-19 17:15 UTC, dzmitry-struk-surf commented on docs/architecture_and_project_structure.md
> +                {feature_name}_flow.dart
`{feature_name}_flow.dart` is an entry point for the feature (or sub_feature) so it should be here in `else` case and inside sub-feature's folder when we have a sub-feature.

2024-02-19 17:16 UTC, dzmitry-struk-surf commented on docs/architecture_and_project_structure.md
> +              - mappers
Yep, sorry.

2024-02-19 17:17 UTC, dzmitry-struk-surf commented on docs/architecture_and_project_structure.md
> +                        - model
`flow` is an entry point for the feature (or sub-feature).

2024-02-21 06:59 UTC, dzmitry-struk-surf requested changes

2024-02-21 06:59 UTC, dzmitry-struk-surf commented on docs/architecture_and_project_structure.md
> +    - converters - classes for mapping data from DTO in entity and vice versa. These classes extends the abstract class `Converter`.
```suggestion
    - converters - classes for mapping data from DTO in entity and vice versa. These classes extend the abstract class `Converter`.
```

2024-02-21 06:59 UTC, dzmitry-struk-surf commented on docs/architecture_and_project_structure.md
> +    - {sub_feature_name/screen_name} - screens or sub-features relevant to the feature, with each screen in a separate self-titled folder containing the following in separate files:
```suggestion
    - {sub_feature_name/screen_name} - screens or sub-features relevant to the feature, with each screen or sub-feature in a separate self-titled folder containing the following in separate files:
```

2024-02-21 09:25 UTC, dzmitry-struk-surf approved these changes

2024-02-21 09:26 UTC, merged