feat: Added uikit
surfstudio/surf-flutter-app-template pull request #71
Opened 2024-02-08 12:16 UTC by Evgenia-bit

## Changes
- uikit structure is designed
- added basic components

## Checklist for self-check
- [x] Commits and PRs have been filed according to [the rules on the project](https://github.com/surfstudio/surf-flutter-app-template#workflow-in-a-repository).
- [x] The author is marked as an assigne and assigned mandatory reviewers.
- [x] Required labels marked
- [ ] Specified related tasks and/or related PRs.
- [x] Specified Changes.
- [ ] Attached videos/screenshots demonstrating the fix/feature.
- [x] All unspecified fields in the PR description deleted.
- [ ] New code covered by tests.

## Checklist for reviewers
- [ ] CI passed successfully _(with a green check mark)_.
- [ ] PR is atomic, by volume no more than 400 (+-) corrected lines (not including codogen).

Design:
- [ ] System design corresponds to the agreements on structure and architecture on the project.
- [ ] The code is decomposed into necessary and sufficient components.

Functionality:
- [ ] The code solves the problem.
- [ ] Any changes to the user interface are reasonable and look good.

Complexity:
- [ ] The code is clear, easy to read, functions are small, no more than 50 lines.
- [ ] The logic is not overcomplicated, there is no overengineering (no code sections that may be needed in the future, but no one knows about it).

Tests:
- [ ] Updated or added tests for mandatory components.
- [ ] The tests are correct, helpful, and well designed/developed.

Naming:
- [ ] The naming of variables, methods, classes and other components is understandable.

Comments:
- [ ] The comments are understandable and helpful.

Documentation:
- [ ] All labels are correct
- [ ] Technical documentation updated (after approval, updates last reviewer).

2024-02-13 08:07 UTC, Sadhorsephile commented on lib/uikit/alerts/app_alert.dart
> +        actions: actions.map((action) => action.build(context)).toList(),
nit: `actions` can be moved to local var instead of duplicating code

2024-02-13 08:07 UTC, Sadhorsephile commented on lib/uikit/buttons/scaled_gesture_detector.dart
> +    if (widget.onTap == null) {
you can use `ConditionalWrapper` here

2024-02-13 08:07 UTC, Sadhorsephile commented on pubspec.yaml
> +  cached_network_image: ^3.3.1
need to remove `^`

2024-02-19 07:13 UTC, dzmitry-struk-surf requested changes

2024-02-19 07:13 UTC, dzmitry-struk-surf commented on lib/uikit/buttons/scaled_gesture_detector.dart
> +  late bool isOnPress;
nit:
```suggestion
  late bool isPressed;
```

2024-02-19 07:13 UTC, dzmitry-struk-surf commented on lib/uikit/buttons/scaled_gesture_detector.dart
> +        behavior: HitTestBehavior.opaque,
I think we should add it to the `ScaledGestureDetector`.

2024-02-19 07:13 UTC, dzmitry-struk-surf commented on lib/uikit/buttons/scaled_gesture_detector.dart
> +  final ValueChanged<bool>? isOnPressChanged;
Why do we need this callback? I think it is redundant as the scale logic is handled by the widget itself.

2024-02-19 17:20 UTC, dzmitry-struk-surf approved these changes

2024-02-19 17:20 UTC, dzmitry-struk-surf commented
Check a merge conflict, please, and the pr is ready to be merged.

2024-02-20 10:23 UTC, dzmitry-struk-surf approved these changes

2024-02-20 10:23 UTC, merged