feat: Updated analytics version
surfstudio/surf-flutter-app-template pull request #74
Opened 2024-02-12 13:56 UTC by Evgenia-bit

## Changes
- updated analytic version

## Checklist for self-check
- [x] Commits and PRs have been filed according to [the rules on the project](https://github.com/surfstudio/surf-flutter-app-template#workflow-in-a-repository).
- [x] The author is marked as an assigne and assigned mandatory reviewers.
- [x] Required labels marked
- [ ] Specified related tasks and/or related PRs.
- [x] Specified Changes.
- [ ] Attached videos/screenshots demonstrating the fix/feature.
- [x] All unspecified fields in the PR description deleted.
- [ ] New code covered by tests.

## Checklist for reviewers
- [ ] CI passed successfully _(with a green check mark)_.
- [ ] PR is atomic, by volume no more than 400 (+-) corrected lines (not including codogen).

Design:
- [ ] System design corresponds to the agreements on structure and architecture on the project.
- [ ] The code is decomposed into necessary and sufficient components.

Functionality:
- [ ] The code solves the problem.
- [ ] Any changes to the user interface are reasonable and look good.

Complexity:
- [ ] The code is clear, easy to read, functions are small, no more than 50 lines.
- [ ] The logic is not overcomplicated, there is no overengineering (no code sections that may be needed in the future, but no one knows about it).

Tests:
- [ ] Updated or added tests for mandatory components.
- [ ] The tests are correct, helpful, and well designed/developed.

Naming:
- [ ] The naming of variables, methods, classes and other components is understandable.

Comments:
- [ ] The comments are understandable and helpful.

Documentation:
- [ ] All labels are correct
- [ ] Technical documentation updated (after approval, updates last reviewer).

2024-02-13 08:15 UTC, Sadhorsephile approved these changes

2024-02-14 04:47 UTC, maxim-sysoev commented on lib/features/app/di/app_scope.dart
> +  AnalyticService get analyticsService;
It is better to set type `AnalyticActionPerformer` so that you cannot add a new strategy to `AnalyticService` anywhere in the application

2024-02-19 07:18 UTC, dzmitry-struk-surf requested changes

2024-02-19 07:18 UTC, dzmitry-struk-surf commented on lib/features/app/di/app_scope.dart
> +      AmplitudeAnalyticStrategy(MockAmplitudeAnalytics()),
Let's remove Amplitude analytics from template, I think it is redundant, one example with Firebase it enough.

2024-02-22 06:37 UTC, dzmitry-struk-surf approved these changes

2024-02-22 06:37 UTC, merged